### ISSUE TITLE
Support .perldb or other method of configuring the debugger on startup

### ISSUE THREAD

**Issue by gbegen** [Camelcade/Perl5-IDEA-Debugger#21]
In my .perldb file for the command line debugger, I have the following line:

    # don't step into Moose itself
    use DB::Skip pkgs => [ qr/^(?:Moose|Eval::Closure|Class::MOP)/ ];

With this debugger, I have to paste that code into the evaluate expression dialog box every time I run the debugger. It would be nice to have a place to put code that runs as the debugger starts up every time.

**Comment by hurricup** [comment]
http://evstigneev.com/IDEA-Perl5-2.102.zip 
cpan HURRICUP/Devel-Camelcadedb-1.6.1.5.tar.gz

Should add init code support and fix problem with port configuration
