### ISSUE TITLE
Devel::Camelcadedb version 2017.1 is not compatible

### ISSUE THREAD

**Issue by kelvenchi** [Camelcade/Perl5-IDEA-Debugger#30]
I have installed the Devel::Camelcadedb and it's version is 2017.1 but the debugger show me an error

> 1:40	Incorrect Devel::Camelcadedb version: Current plugin version requires Devel::Camelcadedb version 1.6.1.x, but we've got 2017.1. Please install appropriate version from CPAN.

Can you fix this problem?

**Comment by hurricup** [comment]
Sorry, this going to be fixed in next version. Now you may change it manually in pm file or install appropriate version from CPAN.

**Comment by evgpisarchik** [comment]
As an ad-hoc solution I changed **2017.1** to "1.6.1.1" here  https://github.com/Camelcade/Perl5-IDEA-Debugger/blob/master/lib/Devel/Camelcadedb.pm and built again.

Debugger started to work after that.

**Comment by arslan-anwar** [comment]
I am still getting this issue. I also update the file and install new version but still getting the same issue. :( please help

Incorrect Devel::Camelcadedb version: Current plugin version requires Devel::Camelcadedb version 2018.3x, but we've got v2019.1. Please install appropriate version from CPAN.

**Comment by hurricup** [comment]
@arslan-anwar it says you what to do. Install proper version of debugging module. Or upgrade ide & plugin to the actual one.
