### ISSUE TITLE
syntax error at /usr/local/share/perl5/Devel/Camelcadedb.pm line 38, near "use constant {     # debugger enabled     "

### ISSUE THREAD

**Issue by mciprijanovic** [Camelcade/Perl5-IDEA-Debugger#31]
Debugger won't start with error in subject

IDEA 2017.1.4
Perl plugin 2017.1.2
Camelcade 2017.1
JRE 1.8.0.
Perl 5.10.1.
OS: CentOS

**Comment by hurricup** [comment]
What version of the CentOS?
Have you tried to debug something simple? like `print 'hello world?';`?

**Comment by mciprijanovic** [comment]
I just removed commented lines from Camelcadedb file and it now works. So from this code:

use constant {
    # debugger enabled
    DEBUG_DEFAULT_FLAGS **# 0x73f**
       => DEBUG_ALL & ~(DEBUG_USE_SUB_ADDRESS|DEBUG_REPORT_GOTO),
    # instrument code, but don't call DB::DB (see sub disable for DB::sub)
    DEBUG_PREPARE_FLAGS **# 0x73c**
       => DEBUG_ALL & ~(DEBUG_USE_SUB_ADDRESS|DEBUG_REPORT_GOTO|DEBUG_SINGLE_STEP_ON),
};

I removed bolded parts (comments # 0x73f and # 0x73c) and now this part of code  in Camelcadedb file looks like this:

use constant {
    # debugger enabled
    DEBUG_DEFAULT_FLAGS => DEBUG_ALL & ~(DEBUG_USE_SUB_ADDRESS|DEBUG_REPORT_GOTO),
    # instrument code, but don't call DB::DB (see sub disable for DB::sub)
    DEBUG_PREPARE_FLAGS => DEBUG_ALL & ~(DEBUG_USE_SUB_ADDRESS|DEBUG_REPORT_GOTO|DEBUG_SINGLE_STEP_ON),
};

Now it works. So just comments after code made a problem.

**Comment by hurricup** [comment]
Funny. Seems it was a bug back than. Thank you.  Will fix.
