### ISSUE TITLE
Devel::Camelcadedb version not parsed correctly

### ISSUE THREAD

**Issue by arpyzo** [Camelcade/Perl5-IDEA-Debugger#33]
Trying to connect to remote Perl Debugger and receiving:
```
Incorrect Devel::Camelcadedb version: Current plugin version requires Devel::Camelcadedb version 2017.1x, but weve got {1}. Please install appropriate version from CPAN.
```
Running netcat indicates that the remote debug server is running as expected:
```
nc -v 192.168.10.10 12345
Connection to 192.168.10.10 port 12345 [tcp/italk] succeeded!
{"version":"v2017.100.3","event":"READY"}
```
Double-checked with tcpdump that IDEA was reaching out to the correct IP.

Client side:
macOS High Sierra 10.13.3
IntelliJ IDEA Community 2017.3.4 (#IC-173.4548.28)
Perl Plugin 2017.5
Java 1.8.0_152-release-1024-b11 x86_64 (bundled with IDEA)

Server Side:
Devel::Camelcadedb v2017.100.3

**Comment by hurricup** [comment]
Please, use ana actual version of the plugin. Should work fine.

**Comment by hurricup** [comment]
It seems that you've set up from the github, not from CPAN.

**Comment by hurricup** [comment]
Feel free to build a plugin from the github. Should work fine. Thank you for report.

**Comment by arpyzo** [comment]
I apologize, but I don't understand. 

The IDEA Perl5 plugin was installed via the plugin manager from a repository.

Devel::Camelcadedb was downloaded from Github and installed using make. Are you saying it would make a difference if I installed it via CPAN instead? 

I'm certainly willing to try this, but the netcat output seems to indicate that Devel::Camelcadedb is producing the expected output, and that the problem is on the IDE Perl5 plugin side.

**Comment by hurricup** [comment]
Yes, There is an unreleased change of the perl module. 
You may install a module from the cpan or install the plugin from the github 173 branch. 
See readme for instructions.

**Comment by arpyzo** [comment]
Installing from CPAN has gotten me past this issue. Thank you for your help.
