### ISSUE TITLE
Can't locate Devel/Camelcadedb.pm

### ISSUE THREAD

**Issue by aldabrada** [Camelcade/Perl5-IDEA-Debugger#37]
* IDE name and version, including build, (e.g. `#IU-143.2370`, available in `Help: About` menu)
  * Perl5 plugin version (available in `File: Settings: Plugins` menu)
  * `Devel::Camelcadedb` module version (see `cpan -D Devel::Camelcadedb`)
  * JRE version (e.g. `Oracle 1.8.0_91-b14`, see `java --version`)
  * Perl version (e.g. `Strawberry Perl (v5.22.0) built for MSWin32-x64-multi-thread`, see `perl -v`)

[https://imgur.com/gallery/ryjcCJ6](https://imgur.com/gallery/ryjcCJ6)

  * Your OS name and version

Windows 7 Enterprise

When trying to debug a simple script like this one:

```
#!/usr/bin/perl
use strict;
use warnings;

print "hi NAME\r\n";
print "hi NAME\r\n";
```
I am getting this error:

> Listening on localhost:51187...
> C:\Dwimperl\perl\bin\perl.exe -d:Camelcadedb C:\mpath\test.pl
> Can't locate Devel/Camelcadedb.pm in @INC (@INC contains: C:/Dwimperl/perl/site/lib C:/Dwimperl/perl/vendor/lib C:/Dwimperl/perl/lib .).
> BEGIN failed--compilation aborted.
> 
> Process finished with exit code 2
> Disconnected

Can you tell me what's wrong with Camelcadedb.pm?

**Comment by hurricup** [comment]
You need to install it
